### ISSUE TITLE
service "contracts-env" is not running container #1

### ISSUE THREAD

**Issue by lipingx** [aave/lens-protocol#134]
When I follow https://github.com/aave/lens-protocol/issues/73, and run  "export USERID=$UID && docker-compose build && docker-compose exec -u 0 contracts-env bash", I got "service "contracts-env" is not running container #1". 

Any idea how to fix this? Thanks .

**Comment by lipingx** [comment]
solved by running
export USERID=$UID && docker-compose build && docker-compose run --name lens contracts-env bash

and in another terminal "docker-compose exec -u 0 contracts-env bash" 
Then npm run test would work without the permission issue.

**Comment by iamcryptoboi** [comment]
In case others are still having issues, I got the following to work:
export USERID=$UID && docker-compose build && docker-compose run -u 0 --name lens contracts-env bash
