### ISSUE TITLE
Lens API docs are out-of-sync

### ISSUE THREAD

**Issue by liamzebedee** [aave/lens-protocol#23]
The `Followed` event is [documented here](https://docs.lens.dev/docs/events#followed) despite not being present in any code in `main`. Are the docs out of sync?

AFAICS it is only implemented in this feature branch here - https://github.com/aave/lens-protocol/pull/16.

**Comment by Zer0dot** [comment]
Well spotted! We removed this event because we already have the `FollowNFTTransferred` event, so it's redundant. Removing from the docs now!
