### ISSUE TITLE
[Question] JSON metadata for Lens Profile NFT

### ISSUE THREAD

**Issue by rootulp** [aave/lens-protocol#26]
I have a question after reading this

> Profiles have a specific URI associated with them, which is meant to include metadata, such as a link to a profile picture or a display name for instance, the JSON standard for this URI is not yet determined.

Is JSON metadata for Lens profile expected to conform to [EIP-721](https://eips.ethereum.org/EIPS/eip-721) Metadata JSON Schema? If not, what other options are being considered?

**Comment by donosonaumczuk** [comment]
Hey @rootulp ! Yes, it will conform EIP-712 metadata JSON schema. Pull request #24 implements `tokenURI` function.

**Comment by rootulp** [comment]
Awesome thanks for clarifying!
