### ISSUE TITLE
Cannot run docker with new command: operation not permitted

### ISSUE THREAD

**Issue by Ataxia123** [aave/lens-protocol#71]
Successfully built 21eb1607fcb7
Successfully tagged lens-protocol_contracts-env:latest
Creating lens-protocol_contracts-env_run ... done
standard_init_linux.go:228: exec user process caused: operation not permitted
ERROR: 1

**Comment by qwolphin** [comment]
```yaml
    security_opt:
      - no-new-privileges
```

You can try if removing those line in `docker-compose.yml` will work for you

**Comment by Ataxia123** [comment]
yeah it did thanks!
