### ISSUE TITLE
The npm run full-deploy-local gives me an error

### ISSUE THREAD

**Issue by siquike** [aave/lens-protocol#92]
Hi. The `npm run full-deploy-local` command from the docs (https://docs.lens.dev/docs/deploying-the-protocol) gives me a 

```
Error HH108: Cannot connect to the network localhost.
Please make sure your node is running, and check your internet connection and networks config 
```

error. Tried `npx hardhat node` in my other terminal first. Also tried `npx hardhat node --hostname 127.0.0.1`.

Please help!

**Comment by siquike** [comment]
I figured out the issue. I'm a noob to docker. The problem was my two terminals were not within the same container.

**Comment by Zer0dot** [comment]
Happy to hear it! Closing this for now, sorry we had some Docker issues earlier on, everything should work better now!
